{% set name = "appmar" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/appmar-{{ version }}.tar.gz
  sha256: 15a3e2217454be257108bfa0d55148a0876ac8cd1302c71aedec532c2da35b8e

build:
  number: 1
  noarch: python
  entry_points:
    - appmar = appmar.appmar:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cartopy
    - cfgrib
    - gdal
    - kneed
    - matplotlib-base ==3.2.*
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - scipy
    - wxpython
    - pillow
    - xarray

test:
  imports:
    - appmar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cemanetwork/appmar
  summary: Python program for marine climate analysis.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dact221
